version: "3"
services:
        db:
                image : mysql
                ports:
                        - "3333:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=amt
                        - MYSQL_USER=user
                        - MYSQL_PASSWORD=pass
                volumes:
                        - "./db:/var/lib/mysql"
        javaee:
                build: ./app
                ports: 
                        - "8080:8080"
                        - "4848:4848"
                depends_on: 
                        - db
                environment:
                        - DB_HOST=db


